### ISSUE TITLE
Pulling all thaiCERT card data

### ISSUE THREAD

**Issue by adchdev** [tropChaud/Categorized-Adversary-TTPs#1]
I've noticed that this dataset has 124 rows whereas the total number of threat actors on the thaiCERT website is over 400. I assume this is because this dataset only maps those actors that also have a MITRE profile.

However, I would like to pull the entire thaiCERT dataset, but using [this link](https://apt.etda.or.th/cgi-bin/getmisp.cgi?o=g) provided on its homepage only provides columns like the group's name, description and country. It doesn't provide the data on motivation, sector, country etc.

It appears the only way to get that data is to pull the JSON file from each actor's card, but I would like to avoid doing that 400+ times for each actor. Is there a better way to do this based on your experience with the thaiCERT dataset?

**Comment by tropChaud** [comment]
I'm sorry that I just saw this now. If you are still interested in the answer (and didn't figure it out yet) - yes, you are correct that my dataset only included those groups with ATT&CK TTPs, but there is another way to pull the data down at scale generally.

See the `tgc-actors.json` file linked [here](https://apt.etda.or.th/cgi-bin/aptgroups.cgi) under the `MISP Users` header, or the direct link here: https://apt.etda.or.th/cgi-bin/getmisp.cgi?o=g

**Comment by adchdev** [comment]
> 

Thanks for the reply. I did pull the JSON from the thaiCERT website but these are the only columns it shows in my Power BI:

![actors](https://user-images.githubusercontent.com/83618043/220947683-f9af4c9c-e480-476a-ad10-cb0d2e4c3b5a.PNG)

There's no motivation, victim industries, victim countries etc like in the threat group cards or in your merged dataset.

I don't want to load each threat group card's JSON 400 times...

**Comment by AbeWinters** [comment]
@acwh0110 Note that the victim industries and countries are named different in this JSON file from https://apt.etda.or.th/cgi-bin/getmisp.cgi?o=g 

They are called `cfr-target-category` and `cfr-suspected-victims` respectively 

See the image below
![image](https://user-images.githubusercontent.com/23054445/226943095-2c73224e-fc24-491d-89fd-c82dfd2e996a.png)
 
If you cannot access the actor data in this JSON, try expanding the top level `values` list. This list contains all the actors.
